/**
 * Style Dictionary build configuration
 *
 * Reads W3C DTCG tokens from tokens/ and outputs CSS custom properties
 * wrapped in Tailwind v4 @theme block.
 *
 * - Base tokens: tokens/base.json -> dist/tokens.css (@theme { ... })
 * - CJK overrides: tokens/overrides/cjk.json -> dist/tokens-cjk.css (:lang(ja) { ... })
 *
 * Usage: pnpm build:tokens
 */
import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";

register(StyleDictionary);

/**
 * Custom transform: name/tailwind-compat
 *
 * Strips "semantic" from color token paths so that
 * `color.semantic.primary` → `--color-primary` (not `--color-semantic-primary`).
 * This ensures Tailwind v4's `bg-primary` → `var(--color-primary)` works.
 */
StyleDictionary.registerTransform({
  name: "name/tailwind-compat",
  type: "name",
  transform: (token) => {
    // token.path = ["color", "semantic", "primary"] → remove "semantic"
    const path = [...token.path];
    if (path[0] === "color" && path[1] === "semantic") {
      path.splice(1, 1); // remove "semantic"
    }
    return path.join("-");
  },
});

/**
 * Custom format: css/tailwind-theme
 *
 * Outputs CSS variables inside a Tailwind v4 `@theme { ... }` block
 * instead of the default `:root { ... }` selector.
 */
StyleDictionary.registerFormat({
  name: "css/tailwind-theme",
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map((token) => `  --${token.name}: ${token.$value ?? token.value};`)
      .join("\n");
    return `/* Generated by Style Dictionary — do not edit manually */\n@theme {\n${vars}\n}\n`;
  },
});

/**
 * Custom format: css/lang-ja
 *
 * Outputs CSS variables inside a `:lang(ja) { ... }` selector
 * for CJK typography overrides.
 */
StyleDictionary.registerFormat({
  name: "css/lang-ja",
  format: ({ dictionary }) => {
    const vars = dictionary.allTokens
      .map((token) => `  --${token.name}: ${token.$value ?? token.value};`)
      .join("\n");
    return `/* Generated by Style Dictionary — CJK overrides, do not edit manually */\n:lang(ja) {\n${vars}\n}\n`;
  },
});

// --- Base tokens ---
const sdBase = new StyleDictionary({
  source: ["tokens/base.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    css: {
      transformGroup: "tokens-studio",
      transforms: ["name/tailwind-compat"],
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/tailwind-theme",
        },
      ],
    },
  },
});

await sdBase.cleanAllPlatforms();
await sdBase.buildAllPlatforms();

// --- CJK overrides ---
const sdCjk = new StyleDictionary({
  source: ["tokens/overrides/cjk.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    css: {
      transformGroup: "tokens-studio",
      transforms: ["name/tailwind-compat"],
      buildPath: "dist/",
      files: [
        {
          destination: "tokens-cjk.css",
          format: "css/lang-ja",
        },
      ],
    },
  },
});

await sdCjk.cleanAllPlatforms();
await sdCjk.buildAllPlatforms();
