/**
 * Style Dictionary config for elxea Design System
 * Transforms W3C DTCG tokens (base.json) → CSS custom properties
 * HEX colors are converted to OKLCH color space
 */
import StyleDictionary from "style-dictionary";

// --- HEX → OKLCH conversion utilities ---

function srgbToLinear(c) {
  return c <= 0.04045 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
}

function linearToXyz(r, g, b) {
  return {
    x: 0.4124564 * r + 0.3575761 * g + 0.1804375 * b,
    y: 0.2126729 * r + 0.7151522 * g + 0.0721750 * b,
    z: 0.0193339 * r + 0.1191920 * g + 0.9503041 * b,
  };
}

function xyzToOklab(x, y, z) {
  const l_ = Math.cbrt(0.8189330101 * x + 0.3618667424 * y - 0.1288597137 * z);
  const m_ = Math.cbrt(0.0329845436 * x + 0.9293118715 * y + 0.0361456387 * z);
  const s_ = Math.cbrt(0.0482003018 * x + 0.2643662691 * y + 0.6338517070 * z);
  return {
    L: 0.2104542553 * l_ + 0.7936177850 * m_ - 0.0040720468 * s_,
    a: 1.9779984951 * l_ - 2.4285922050 * m_ + 0.4505937099 * s_,
    b: 0.0259040371 * l_ + 0.7827717662 * m_ - 0.8086757660 * s_,
  };
}

function oklabToOklch(L, a, b) {
  const C = Math.sqrt(a * a + b * b);
  let H = (Math.atan2(b, a) * 180) / Math.PI;
  if (H < 0) H += 360;
  return { L, C, H };
}

function hexToOklch(hex) {
  const h = hex.replace("#", "");
  const r = srgbToLinear(parseInt(h.slice(0, 2), 16) / 255);
  const g = srgbToLinear(parseInt(h.slice(2, 4), 16) / 255);
  const b = srgbToLinear(parseInt(h.slice(4, 6), 16) / 255);

  const xyz = linearToXyz(r, g, b);
  const lab = xyzToOklab(xyz.x, xyz.y, xyz.z);
  const lch = oklabToOklch(lab.L, lab.a, lab.b);

  // Round to 3 decimal places
  const L = Math.round(lch.L * 1000) / 1000;
  const C = Math.round(lch.C * 1000) / 1000;
  const H = Math.round(lch.H * 10) / 10;

  // Pure black/white: no chroma or hue needed
  if (C < 0.001) {
    return `oklch(${L} 0 0)`;
  }
  return `oklch(${L} ${C} ${H})`;
}

// --- Register custom transform: HEX → OKLCH ---

StyleDictionary.registerTransform({
  name: "color/hex-to-oklch",
  type: "value",
  transitive: true,
  filter: (token) => token.$type === "color",
  transform: (token) => {
    const val = token.$value ?? token.value;
    if (typeof val === "string" && val.startsWith("#")) {
      return hexToOklch(val);
    }
    return val;
  },
});

// --- Custom format: @theme block for Tailwind CSS 4.x ---

StyleDictionary.registerFormat({
  name: "css/theme-block",
  format: ({ dictionary }) => {
    const lines = ["/* Generated by Style Dictionary -- do not edit manually */", "@theme {"];

    const tokens = dictionary.allTokens;
    let currentGroup = "";

    for (const token of tokens) {
      // Group separator comment
      const group = token.path[0];
      if (group !== currentGroup) {
        if (currentGroup) lines.push("");
        currentGroup = group;
      }

      // Build CSS variable name from path
      // color.semantic.background → --color-background
      // color.brand.gray-20 → --color-brand-gray-20
      let varName;
      if (token.path[0] === "color" && token.path[1] === "semantic") {
        // Semantic colors: flatten to --color-{name} for shadcn/ui compatibility
        varName = `--color-${token.path.slice(2).join("-")}`;
      } else if (token.path[0] === "color" && token.path[1] === "brand") {
        varName = `--color-brand-${token.path.slice(2).join("-")}`;
      } else {
        varName = `--${token.path.join("-")}`;
      }

      const value = token.$value ?? token.value;
      lines.push(`  ${varName}: ${value};`);
    }

    lines.push("}");
    return lines.join("\n") + "\n";
  },
});

// --- Custom format: CJK overrides ---

StyleDictionary.registerFormat({
  name: "css/cjk-overrides",
  format: ({ dictionary }) => {
    const lines = [
      "/* Generated by Style Dictionary -- CJK overrides, do not edit manually */",
      ":lang(ja) {",
    ];

    // CJK-specific typography overrides
    // Heading fonts: same as base (aktiv-grotesk-extended, dnp-shuei-gothic-gin-std)
    // Body fonts: same as base (aktiv-grotesk, dnp-shuei-gothic-gin-std)
    // CJK needs wider line-height for readability

    const headingFamily = "aktiv-grotesk-extended, dnp-shuei-gothic-gin-std, sans-serif";
    const bodyFamily = "aktiv-grotesk, dnp-shuei-gothic-gin-std, sans-serif";
    const monoFamily = "'SF Mono', Menlo, monospace";

    const cjkStyles = [
      { name: "h1", weight: 600, size: "3rem", lh: "1.4", family: headingFamily },
      { name: "h2", weight: 600, size: "2rem", lh: "1.5", family: headingFamily },
      { name: "h3", weight: 600, size: "1.5rem", lh: "1.55", family: headingFamily },
      { name: "h4", weight: 600, size: "1.25rem", lh: "1.6", family: headingFamily },
      { name: "h5", weight: 500, size: "1rem", lh: "1.7", family: headingFamily },
      { name: "h6", weight: 500, size: "0.875rem", lh: "1.8", family: headingFamily },
      { name: "body-01", weight: 400, size: "1rem", lh: "1.8", family: bodyFamily },
      { name: "body-02", weight: 400, size: "0.875rem", lh: "1.8", family: bodyFamily },
      { name: "caption", weight: 400, size: "0.75rem", lh: "1.75", family: bodyFamily },
    ];

    for (const s of cjkStyles) {
      lines.push(`  --typography-size-${s.name}-cjk: ${s.size};`);
      lines.push(`  --typography-lineHeight-${s.name}-cjk: ${s.lh};`);
    }

    lines.push("}");
    return lines.join("\n") + "\n";
  },
});

// --- Config ---

const config = {
  source: ["tokens/base.json"],
  platforms: {
    css: {
      transformGroup: "css",
      transforms: ["color/hex-to-oklch"],
      buildPath: "dist/",
      files: [
        {
          destination: "tokens.css",
          format: "css/theme-block",
        },
        {
          destination: "tokens-cjk.css",
          format: "css/cjk-overrides",
        },
      ],
    },
  },
};

export default config;
